version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "develop"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    target-branch: "develop"
    cooldown:
      default-days: 7
