@startuml
|room master|
start
:create room;
floating note left: <<usecase>>\ncreate room
|#AntiqueWhite|users|
:enter the room;
floating note right:  <<usecase>>\nadd user
repeat
fork
|room master|
:pick a card;
floating note left:  <<usecase>>\nregister picked the card
fork again
|users|
:pick a card;
endfork
fork
|room master|
:receive the result;
floating note left:  <<usecase>>\nnotify the result
fork again
|users|
:receive the result;
end fork
:choose continue or not;
floating note right:  <<usecase>>\nreflesh the porker data
repeatwhile (continue)
end
@enduml