@startuml
|room master|
start
:create room;
floating note left: <<usecase>>\ncreate a new room
|#AntiqueWhite|users|
:enter to the room;
floating note right:  <<usecase>>\nadd a new user to the room
repeat
fork
|room master|
:choose a card;
floating note left:  <<usecase>>\nregister the choosed card
fork again
|users|
:choose a card;
endfork
:reset the choosed card data;
floating note right:  <<usecase>>\nreflesh the poker
repeatwhile (reset)
end
@enduml