@startuml

[*] --> created: create a new room
state created {
    [*] --> choosing_card: add a new user to the room
    choosing_card --> choosing_card: some player refreshes the poker
    choosing_card --> choosed_card: the user choosed a card
    choosed_card --> choosing_card: some player refreshes the poker
    choosing_card --> leaved: the user leaves
    choosed_card --> leaved: the user leaves
    leaved --> choosing_card: the leaved user backs
}

created --> closed: expired the room

@enduml
