@startuml
rectangle leave {
    :user:
    user -- (leave)

    note right of (leave)
    ユーザが途中で退出したくなった場合、
    簡単な操作で退出できる
    end note

    (leave room)<<usecase>>
    (leave)--(leave room)
}

rectangle reenter {
    :user2:
    user2 -- (reenter)

    note right of (reenter)
    一度退出したユーザが再度部屋に入ることができる
    end note

    (reenter room)<<usecase>>
    (reenter)--(reenter room)
}

rectangle kick {
    :userA:
    userA-- (kick)
    :userB:
    userB--(kick)

    note right of (kick)
    任意のユーザを退出させることができる
    end note

    (kick user)<<usecase>>
    (kick)--(kick user)
}
@enduml
