@startuml
!include <awslib/AWSCommon>
!include <awslib/AWSSimplified>
!include <awslib/General/User>
!include <awslib/General/Users>
!include <awslib/ApplicationIntegration/AppSync>
!include <awslib/Compute/Lambda>
!include <awslib/Database/DynamoDB>

left to right direction

Users(users, "users", "users of a room")
AppSync(operationMutation, "Operation mutation", "operation")
DynamoDB(operationTable, "Operatoin Table", "event store")
Lambda(rmu, "RMU", "synchronize event to query store")
DynamoDB(roomTable, "Room Table", "query store")
Lambda(mutatePoker, "Mutate Poker", "push room data")
AppSync(pokerMutation, "Poker mutation", "room")
AppSync(pokerSubscription, "Poker subscription", "room")
AppSync(roomQuery, "Room query", "room")

users -right--> operationMutation
operationMutation --> operationTable: dynamo resolver
operationTable .right.> rmu: dynamo stream
rmu --> roomTable: update room table
roomTable .up.> mutatePoker: dynamo stream
mutatePoker -left-> pokerMutation
pokerMutation -> pokerSubscription: none resolver
pokerSubscription <--> users
users <--> roomQuery
roomQuery <--> roomTable: dynamo resolver
@enduml