name: Build backend

on:
  push:
    paths:
      - 'backend/**'

permissions:
  id-token: write
  contents: read

jobs:
  build_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build RoomRMU function
        working-directory: ./backend/lambda/room-rmu
        run: go build -v ./...
      - name: Test RoomRMU function
        working-directory: ./backend/lambda/room-rmu
        run: go test -v ./...

      - name: Build MutateUser function
        working-directory: ./backend/lambda/mutate-user
        run: go build -v ./...
      - name: Test MutateUser function
        working-directory: ./backend/lambda/mutate-user
        run: go test -v ./...

  deploy_to_stg:
    needs: build_lambda
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_STG_ROLE_ARN}}
          aws-region: ap-northeast-1
      - run: yarn install
      - run: yarn workspace salon-backend deploy
