name: Build backend

on:
  push:
    paths:
      - 'backend/**'

permissions:
  id-token: write
  contents: read

jobs:
  build_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Go
        uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
        with:
          go-version: 1.24

      - name: Build RoomRMU function
        working-directory: ./backend/lambda/room-rmu
        run: go build -v ./...
      - name: Test RoomRMU function
        working-directory: ./backend/lambda/room-rmu
        run: go test -v ./...

      - name: Build MutateUser function
        working-directory: ./backend/lambda/mutate-user
        run: go build -v ./...
      - name: Test MutateUser function
        working-directory: ./backend/lambda/mutate-user
        run: go test -v ./...

  deploy_to_stg:
    needs: build_lambda
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{secrets.AWS_STG_ROLE_ARN}}
          aws-region: ap-northeast-1
      - run: yarn install
      - run: yarn workspace salon-backend deploy

  deploy_to_prd:
    needs: build_lambda
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{secrets.AWS_PRD_ROLE_ARN}}
          aws-region: ap-northeast-1
      - run: yarn install
      - run: yarn workspace salon-backend deploy
