name: 'Chromatic'

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Install dependencies
        run: yarn
        working-directory: .
      - name: Publish to Chromatic
        uses: chromaui/action@c93e0bc3a63aa176e14a75b61a31847cbfdd341c # v11.27.0
        with:
          workingDir: frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
